// <auto-generated />
using System;
using E1U2POO.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E1U2POO.API.Migrations
{
    [DbContext(typeof(PlanillaDbContext))]
    partial class PlanillaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("E1U2POO.API.Database.Entities.DetallePlanillaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Bonification")
                        .HasColumnType("TEXT")
                        .HasColumnName("bonificacion");

                    b.Property<string>("Commit")
                        .HasColumnType("TEXT")
                        .HasColumnName("comentarios");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("empleado_id");

                    b.Property<decimal>("ExtraHours")
                        .HasColumnType("TEXT")
                        .HasColumnName("horas_extra");

                    b.Property<decimal>("MountExtraHours")
                        .HasColumnType("TEXT")
                        .HasColumnName("monto_horas_extra");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planilla_id");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_base");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_neto");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("Detalle_Planilla");
                });

            modelBuilder.Entity("E1U2POO.API.Database.Entities.EmpleadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<DateTime>("DateContrat")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_contratacio");

                    b.Property<string>("Departament")
                        .HasColumnType("TEXT")
                        .HasColumnName("departamento");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("documento");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("apellidos");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_base");

                    b.Property<string>("WorkState")
                        .HasColumnType("TEXT")
                        .HasColumnName("puesto_de_trabajo");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("E1U2POO.API.Database.Entities.PlanillaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo");

                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.ToTable("Planilla");
                });

            modelBuilder.Entity("E1U2POO.API.Database.Entities.DetallePlanillaEntity", b =>
                {
                    b.HasOne("E1U2POO.API.Database.Entities.EmpleadoEntity", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E1U2POO.API.Database.Entities.PlanillaEntity", "Planilla")
                        .WithMany()
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });
#pragma warning restore 612, 618
        }
    }
}
